name: Build Windows EXE

on:
  push:
    branches: [ main ]  # Сборка будет запускаться при каждом пуше в ветку main
  workflow_dispatch:      # Позволяет запускать сборку вручную через вкладку Actions

jobs:
  build:
    runs-on: windows-latest  # Используем виртуальную машину с Windows

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10' # Укажите вашу версию Python

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build EXE with PyInstaller
      run: |
        pyinstaller --onefile --windowed main.py
      # Замените main.py на название вашего главного файла

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: windows-executable
        path: dist/*.exe